// pastebin-front/src/app/show/CodeView.tsx
import React, { useEffect, useRef } from "react";
import prism from "./prism";

interface Props {
    lang: string
    content: string
}

const CodeView: React.FC<Props> = ({ lang, content }: Props) => {
    const prismClass = `language-${lang}`;

    const divRef = useRef<HTMLDivElement>(null);

    useEffect(() => {
        setImmediate(() => {
            if (divRef.current) {
                prism.highlightAllUnder(divRef.current, false);
            }
        });
    });

    return (
        <div style={{ width: "100%" }} ref={divRef}>
            <pre>
                <code className={prismClass}>
                    {content}
                </code>
            </pre>
        </div>
    );
};

export default CodeView;

// pastebin-front/src/components/CodeView.vue
<template>
    <div class="line-numbers" style="width: 100%" ref="contentDiv">
        <pre><code :class="prismClass">{{ props.content }}</code></pre>
    </div>
</template>

<script setup lang="ts">
import { computed, ref, toRef } from "vue";
import { useHighlight } from "@/hooks/useHighlight";

const props = defineProps<{
    lang: string;
    content: string;
}>();

const prismClass = computed(() => `language-${props.lang}`);

const contentDiv = ref<HTMLDivElement | null>(null);
useHighlight(contentDiv, toRef(props, "content"));
</script>
